### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by patrickpietens** [dgieselaar/mele#1]
This is not what React is about. You're not supposed to fiddle with the DOM manually. Instead use state and let React re-render its components on state updates. Have a look at Redux/MobX for examples.

**Comment by dgieselaar** [comment]
Doesn't fiddle w/ the DOM. It changes the element tree (the rendering instructions) before it gets to the rendering engine (like react-dom). I need it for a plugin architecture. You're not the first to ask so I'll try to make things clearer.

**Comment by patrickpietens** [comment]
Just out of curiosity, can you give an example of when you would use Mele? Because I can't think of any.

**Comment by dgieselaar** [comment]
Yeah, I'll improve the documents when I have the time.
