### ISSUE TITLE
Build issues?

### ISSUE THREAD

**Issue by alepeino** [dgieselaar/mele#2]
* Nothing gets imported after `import mele from 'react-mele'` (empty object). Maybe because of `"main": "build/index.js"` while Webpack builds to `build/mele.js`?

* When importing directly `import mele from 'react-mele/build/mele'`, I get `ReferenceError: React is not defined`. (I guess this is about the Webpack externals, but I don't have a global `window.React` object, instead I'm using my own webpack build much like the one from create-react-app).

* Even if I try to patch the previous issue by requiring React separately (some CDN, for example) I am getting `TypeError: __WEBPACK_IMPORTED_MODULE_0_react_mele_build_mele_js___default(...) is not a function` (Again the imported `mele` is an empty object).

I really wanted to use this library, and I don't know my way around Webpack to submit a PR...

**Comment by dgieselaar** [comment]
Hi Alejandro, super sorry for the late reply. I've put it on my todo list, and I will make sure this is addressed in the weekend.
